"""New Admin UI Changes

Revision ID: 072837d9b7e8
Revises: 4a8c2d3f5b71
Create Date: 2026-04-02 19:58:36.742604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '072837d9b7e8'
down_revision: Union[str, Sequence[str], None] = '4a8c2d3f5b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruit_rankings', schema=None) as batch_op:
        batch_op.alter_column('raw_inputs_json',
               existing_type=sqlite.JSON(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('normalized_features_json',
               existing_type=sqlite.JSON(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('scoring_method',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_current',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('scored_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_recruit_rankings_application_game_current'))
        batch_op.drop_index(batch_op.f('ix_recruit_rankings_game_current_score'))
        batch_op.drop_index(batch_op.f('uq_recruit_rankings_current_per_application_game'), sqlite_where=sa.text('is_current = 1'))

    with op.batch_alter_table('recruit_reviews', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_recruit_reviews_status_labeled_at'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruit_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recruit_reviews_status_labeled_at'), ['status', 'labeled_at'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'NEW'"),
               existing_nullable=False)

    with op.batch_alter_table('recruit_rankings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_recruit_rankings_current_per_application_game'), ['application_id', 'game_id'], unique=1, sqlite_where=sa.text('is_current = 1'))
        batch_op.create_index(batch_op.f('ix_recruit_rankings_game_current_score'), ['game_id', 'is_current', 'score'], unique=False)
        batch_op.create_index(batch_op.f('ix_recruit_rankings_application_game_current'), ['application_id', 'game_id', 'is_current'], unique=False)
        batch_op.alter_column('scored_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=False)
        batch_op.alter_column('is_current',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=False)
        batch_op.alter_column('scoring_method',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'rules'"),
               existing_nullable=False)
        batch_op.alter_column('normalized_features_json',
               existing_type=sqlite.JSON(),
               server_default=sa.text("'{}'"),
               existing_nullable=False)
        batch_op.alter_column('raw_inputs_json',
               existing_type=sqlite.JSON(),
               server_default=sa.text("'{}'"),
               existing_nullable=False)

    # ### end Alembic commands ###
