"""Roster Rank Display Changes

Revision ID: 12403619f017
Revises: e1b0f67c9d2a
Create Date: 2026-04-28 11:26:19.970966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12403619f017'
down_revision: Union[str, Sequence[str], None] = 'e1b0f67c9d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_game_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', name='uq_player_game_profiles_player_game')
    )
    with op.batch_alter_table('player_game_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_game_profiles_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_game_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_game_profiles_player_id'), ['player_id'], unique=False)

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('must_change_password',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('announcement_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcement_games_game_id'))

    with op.batch_alter_table('esports_announcements', schema=None) as batch_op:
        batch_op.alter_column('is_general',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esports_announcements', schema=None) as batch_op:
        batch_op.alter_column('is_general',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)

    with op.batch_alter_table('announcement_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcement_games_game_id'), ['game_id'], unique=False)

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('must_change_password',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=False)

    with op.batch_alter_table('player_game_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_game_profiles_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_game_profiles_id'))
        batch_op.drop_index(batch_op.f('ix_player_game_profiles_game_id'))

    op.drop_table('player_game_profiles')
    # ### end Alembic commands ###
