"""Phase 1 RBAC

Revision ID: 6050c498ebd2
Revises: 30e361842e30
Create Date: 2026-04-14 02:54:27.970830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6050c498ebd2'
down_revision: Union[str, Sequence[str], None] = '30e361842e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user_game_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_user_id', 'game_id', name='uq_admin_user_game_access_admin_user_id_game_id')
    )
    with op.batch_alter_table('admin_user_game_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_user_game_access_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_user_game_access_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_user_game_access_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_user_game_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_user_game_access_id'))
        batch_op.drop_index(batch_op.f('ix_admin_user_game_access_game_id'))
        batch_op.drop_index(batch_op.f('ix_admin_user_game_access_admin_user_id'))

    op.drop_table('admin_user_game_access')
    # ### end Alembic commands ###
