"""add hearthstone recruit fields

Revision ID: 669a57831bf7
Revises: 7ea7b54dc505
Create Date: 2026-03-25 12:49:43.421756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '669a57831bf7'
down_revision: Union[str, Sequence[str], None] = '7ea7b54dc505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recruit_availability')
    op.drop_table('recruit_game_profiles')
    op.drop_table('recruit_reviews')
    op.drop_table('recruit_rankings')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_recruit_applications_id'), table_name='recruit_applications')
    op.drop_table('recruit_applications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruit_applications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('discord', sa.VARCHAR(), nullable=False),
    sa.Column('current_school', sa.VARCHAR(), nullable=True),
    sa.Column('city_state', sa.VARCHAR(), nullable=True),
    sa.Column('graduation_year', sa.INTEGER(), nullable=True),
    sa.Column('preferred_contact', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruit_applications_id'), 'recruit_applications', ['id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_table('recruit_rankings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('application_id', sa.INTEGER(), nullable=True),
    sa.Column('game_id', sa.INTEGER(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('explanation_json', sqlite.JSON(), nullable=True),
    sa.Column('model_version', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['recruit_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruit_reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('application_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('reviewer_user_id', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['recruit_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruit_game_profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('application_id', sa.INTEGER(), nullable=True),
    sa.Column('game_id', sa.INTEGER(), nullable=True),
    sa.Column('ign', sa.VARCHAR(), nullable=True),
    sa.Column('fortnite_mode', sa.VARCHAR(), nullable=True),
    sa.Column('current_rank_label', sa.VARCHAR(), nullable=True),
    sa.Column('current_rank_numeric', sa.FLOAT(), nullable=True),
    sa.Column('peak_rank_label', sa.VARCHAR(), nullable=True),
    sa.Column('peak_rank_numeric', sa.FLOAT(), nullable=True),
    sa.Column('primary_role', sa.VARCHAR(), nullable=True),
    sa.Column('secondary_role', sa.VARCHAR(), nullable=True),
    sa.Column('tracker_url', sa.VARCHAR(), nullable=True),
    sa.Column('team_experience', sa.BOOLEAN(), nullable=True),
    sa.Column('scrim_experience', sa.BOOLEAN(), nullable=True),
    sa.Column('tournament_experience', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['recruit_applications.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruit_availability',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('application_id', sa.INTEGER(), nullable=True),
    sa.Column('hours_per_week', sa.INTEGER(), nullable=True),
    sa.Column('weeknights_available', sa.BOOLEAN(), nullable=True),
    sa.Column('weekends_available', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['recruit_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
