"""Phase 2 announcement workflow

Revision ID: ec531a935e59
Revises: 6050c498ebd2
Create Date: 2026-04-14 19:38:03.361505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec531a935e59'
down_revision: Union[str, Sequence[str], None] = '6050c498ebd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esports_announcements', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'state',
                sa.String(length=32),
                nullable=False,
                server_default=sa.text("'published'"),
            )
        )
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_admin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_esports_announcements_game_id'), ['game_id'], unique=False)
        batch_op.create_foreign_key(
            "fk_esports_announcements_approved_by_admin_id",
            "admin_users",
            ["approved_by_admin_id"],
            ["id"],
        )

        batch_op.create_foreign_key(
            "fk_esports_announcements_game_id",
            "games",
            ["game_id"],
            ["id"],
        )

    with op.batch_alter_table('esports_announcements', schema=None) as batch_op:
        batch_op.alter_column(
            'state',
            existing_type=sa.String(length=32),
            nullable=False,
            server_default=None,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esports_announcements', schema=None) as batch_op:
        batch_op.drop_constraint('fk_esports_announcements_game_id', type_='foreignkey')
        batch_op.drop_constraint('fk_esports_announcements_approved_by_admin_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_esports_announcements_game_id'))
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by_admin_id')
        batch_op.drop_column('game_id')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
