"""fresh schema

Revision ID: fcab3fb0cada
Revises: 
Create Date: 2026-03-31 15:29:29.856887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcab3fb0cada'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_users_username'), ['username'], unique=True)

    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_id'), ['id'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gamertag', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('major', sa.String(), nullable=True),
    sa.Column('headshot', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_id'), ['id'], unique=False)

    op.create_table('recruit_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('discord', sa.String(), nullable=False),
    sa.Column('current_school', sa.String(), nullable=True),
    sa.Column('city_state', sa.String(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('preferred_contact', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recruit_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recruit_applications_id'), ['id'], unique=False)

    op.create_table('recruit_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('hours_per_week', sa.Integer(), nullable=True),
    sa.Column('weeknights_available', sa.Boolean(), nullable=True),
    sa.Column('weekends_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['recruit_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruit_game_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('ign', sa.String(), nullable=True),
    sa.Column('fortnite_mode', sa.String(), nullable=True),
    sa.Column('ranked_wins', sa.Integer(), nullable=True),
    sa.Column('years_played', sa.Integer(), nullable=True),
    sa.Column('legend_peak_rank', sa.Integer(), nullable=True),
    sa.Column('preferred_format', sa.String(), nullable=True),
    sa.Column('other_card_games', sa.String(), nullable=True),
    sa.Column('gsp', sa.Integer(), nullable=True),
    sa.Column('regional_rank', sa.String(), nullable=True),
    sa.Column('best_wins', sa.String(), nullable=True),
    sa.Column('characters', sa.String(), nullable=True),
    sa.Column('lounge_rating', sa.Integer(), nullable=True),
    sa.Column('preferred_title', sa.String(), nullable=True),
    sa.Column('controller_type', sa.String(), nullable=True),
    sa.Column('playstyle', sa.String(), nullable=True),
    sa.Column('preferred_tracks', sa.String(), nullable=True),
    sa.Column('current_rank_label', sa.String(), nullable=True),
    sa.Column('current_rank_numeric', sa.Float(), nullable=True),
    sa.Column('peak_rank_label', sa.String(), nullable=True),
    sa.Column('peak_rank_numeric', sa.Float(), nullable=True),
    sa.Column('primary_role', sa.String(), nullable=True),
    sa.Column('secondary_role', sa.String(), nullable=True),
    sa.Column('tracker_url', sa.String(), nullable=True),
    sa.Column('team_experience', sa.Boolean(), nullable=True),
    sa.Column('scrim_experience', sa.Boolean(), nullable=True),
    sa.Column('tournament_experience', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['recruit_applications.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruit_rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('explanation_json', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['recruit_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruit_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['recruit_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recruit_reviews')
    op.drop_table('recruit_rankings')
    op.drop_table('recruit_game_profiles')
    op.drop_table('recruit_availability')
    with op.batch_alter_table('recruit_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recruit_applications_id'))

    op.drop_table('recruit_applications')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_id'))

    op.drop_table('players')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_id'))

    op.drop_table('games')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_username'))
        batch_op.drop_index(batch_op.f('ix_admin_users_id'))
        batch_op.drop_index(batch_op.f('ix_admin_users_email'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
